name: CD # Continuous Deployment

on:
  push:
    tags:
      - '[v]?[0-9]+.[0-9]+.[0-9]+'

jobs:

  publish:
    name: Publish GitHub pages
    runs-on: ${{ matrix.job.os }}
    strategy:
      matrix:
        rust: [stable]
        job:
          - os: ubuntu-latest
            os-name: linux
            target: wasm32-unknown-unknown
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.job.target }}
          profile: minimal
          override: true
      - uses: Swatinem/rust-cache@v1
      - name: Install required packages
        run: sudo apt-get update && sudo apt-get install -y pkg-config libx11-dev libxi-dev libgl1-mesa-dev libasound2-dev sqlite3
      - name: Cargo build
        uses: actions-rs/cargo@v1
        env:
          DOWNLOAD_ASSETS: 1
          PATH_ASSETS: assets/
        with:
          command: build
          toolchain: ${{ matrix.rust }}
          args: --release --target ${{ matrix.job.target }}
      - name: Move wasm binary to public directory
        shell: bash
        run: |
          mv ./target/${{ matrix.job.target }}/release/lisensei.wasm ./public/
      - name: Publish public directory to GitHub pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
